/* filecheck.h generated by valac 0.56.17, the Vala compiler, do not modify */

#ifndef __FILECHECK_H__
#define __FILECHECK_H__

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gee.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define FILE_CHECK_TYPE_ANALYZER (file_check_analyzer_get_type ())
#define FILE_CHECK_ANALYZER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FILE_CHECK_TYPE_ANALYZER, FileCheckAnalyzer))
#define FILE_CHECK_ANALYZER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FILE_CHECK_TYPE_ANALYZER, FileCheckAnalyzerClass))
#define FILE_CHECK_IS_ANALYZER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FILE_CHECK_TYPE_ANALYZER))
#define FILE_CHECK_IS_ANALYZER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FILE_CHECK_TYPE_ANALYZER))
#define FILE_CHECK_ANALYZER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FILE_CHECK_TYPE_ANALYZER, FileCheckAnalyzerClass))

typedef struct _FileCheckAnalyzer FileCheckAnalyzer;
typedef struct _FileCheckAnalyzerClass FileCheckAnalyzerClass;
typedef struct _FileCheckAnalyzerPrivate FileCheckAnalyzerPrivate;

struct _FileCheckAnalyzer {
	GTypeInstance parent_instance;
	volatile int ref_count;
	FileCheckAnalyzerPrivate * priv;
};

struct _FileCheckAnalyzerClass {
	GTypeClass parent_class;
	void (*finalize) (FileCheckAnalyzer *self);
};

VALA_EXTERN gpointer file_check_analyzer_ref (gpointer instance);
VALA_EXTERN void file_check_analyzer_unref (gpointer instance);
VALA_EXTERN GParamSpec* file_check_param_spec_analyzer (const gchar* name,
                                            const gchar* nick,
                                            const gchar* blurb,
                                            GType object_type,
                                            GParamFlags flags);
VALA_EXTERN void file_check_value_set_analyzer (GValue* value,
                                    gpointer v_object);
VALA_EXTERN void file_check_value_take_analyzer (GValue* value,
                                     gpointer v_object);
VALA_EXTERN gpointer file_check_value_get_analyzer (const GValue* value);
VALA_EXTERN GType file_check_analyzer_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FileCheckAnalyzer, file_check_analyzer_unref)
VALA_EXTERN FileCheckAnalyzer* file_check_analyzer_new (void);
VALA_EXTERN FileCheckAnalyzer* file_check_analyzer_construct (GType object_type);
VALA_EXTERN GeeArrayList* file_check_analyzer_analyze_directories (FileCheckAnalyzer* self,
                                                       const gchar* dir1,
                                                       const gchar* dir2,
                                                       gint context_size);
VALA_EXTERN GeeArrayList* file_check_analyzer_get_files (FileCheckAnalyzer* self,
                                             const gchar* directory);
VALA_EXTERN gchar* file_check_analyzer_find_corruption (FileCheckAnalyzer* self,
                                            const gchar* file1,
                                            const gchar* file2,
                                            gint context_size);

G_END_DECLS

#endif
