/* filecheck.h generated by valac 0.56.17, the Vala compiler, do not modify */

#ifndef __FILECHECK_H__
#define __FILECHECK_H__

#include <glib-object.h>
#include <glib.h>
#include <gio/gio.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define FILE_CHECK_TYPE_FILE_COMPARATOR (file_check_file_comparator_get_type ())
#define FILE_CHECK_FILE_COMPARATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FILE_CHECK_TYPE_FILE_COMPARATOR, FileCheckFileComparator))
#define FILE_CHECK_FILE_COMPARATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FILE_CHECK_TYPE_FILE_COMPARATOR, FileCheckFileComparatorClass))
#define FILE_CHECK_IS_FILE_COMPARATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FILE_CHECK_TYPE_FILE_COMPARATOR))
#define FILE_CHECK_IS_FILE_COMPARATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FILE_CHECK_TYPE_FILE_COMPARATOR))
#define FILE_CHECK_FILE_COMPARATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FILE_CHECK_TYPE_FILE_COMPARATOR, FileCheckFileComparatorClass))

typedef struct _FileCheckFileComparator FileCheckFileComparator;
typedef struct _FileCheckFileComparatorClass FileCheckFileComparatorClass;
typedef struct _FileCheckFileComparatorPrivate FileCheckFileComparatorPrivate;

struct _FileCheckFileComparator {
	GTypeInstance parent_instance;
	volatile int ref_count;
	FileCheckFileComparatorPrivate * priv;
	gint CONTEXT_SIZE;
};

struct _FileCheckFileComparatorClass {
	GTypeClass parent_class;
	void (*finalize) (FileCheckFileComparator *self);
};

VALA_EXTERN gpointer file_check_file_comparator_ref (gpointer instance);
VALA_EXTERN void file_check_file_comparator_unref (gpointer instance);
VALA_EXTERN GParamSpec* file_check_param_spec_file_comparator (const gchar* name,
                                                   const gchar* nick,
                                                   const gchar* blurb,
                                                   GType object_type,
                                                   GParamFlags flags);
VALA_EXTERN void file_check_value_set_file_comparator (GValue* value,
                                           gpointer v_object);
VALA_EXTERN void file_check_value_take_file_comparator (GValue* value,
                                            gpointer v_object);
VALA_EXTERN gpointer file_check_value_get_file_comparator (const GValue* value);
VALA_EXTERN GType file_check_file_comparator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (FileCheckFileComparator, file_check_file_comparator_unref)
VALA_EXTERN FileCheckFileComparator* file_check_file_comparator_new (void);
VALA_EXTERN FileCheckFileComparator* file_check_file_comparator_construct (GType object_type);
VALA_EXTERN void file_check_file_comparator_compare_directory (FileCheckFileComparator* self,
                                                   GFile* original_dir,
                                                   GFile* corrupted_dir,
                                                   GeeArrayList* results);

G_END_DECLS

#endif
