/* filecheck.c generated by valac 0.56.17, the Vala compiler
 * generated from filecheck.vala, do not modify */

#include "filecheck.h"
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gee.h>
#include <gio/gio.h>
#include <stdio.h>
#include <glib/gstdio.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _FileCheckParamSpecAnalyzer FileCheckParamSpecAnalyzer;

struct _FileCheckParamSpecAnalyzer {
	GParamSpec parent_instance;
};

static gpointer file_check_analyzer_parent_class = NULL;

static void file_check_analyzer_finalize (FileCheckAnalyzer * obj);
static GType file_check_analyzer_get_type_once (void);

FileCheckAnalyzer*
file_check_analyzer_construct (GType object_type)
{
	FileCheckAnalyzer* self = NULL;
	self = (FileCheckAnalyzer*) g_type_create_instance (object_type);
	return self;
}

FileCheckAnalyzer*
file_check_analyzer_new (void)
{
	return file_check_analyzer_construct (FILE_CHECK_TYPE_ANALYZER);
}

GeeArrayList*
file_check_analyzer_analyze_directories (FileCheckAnalyzer* self,
                                         const gchar* dir1,
                                         const gchar* dir2,
                                         gint context_size)
{
	GeeArrayList* results = NULL;
	GeeArrayList* _tmp0_;
	GeeArrayList* files1 = NULL;
	GeeArrayList* _tmp1_;
	GeeArrayList* files2 = NULL;
	GeeArrayList* _tmp2_;
	GeeArrayList* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (dir1 != NULL, NULL);
	g_return_val_if_fail (dir2 != NULL, NULL);
	_tmp0_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, NULL, NULL, NULL);
	results = _tmp0_;
	_tmp1_ = file_check_analyzer_get_files (self, dir1);
	files1 = _tmp1_;
	_tmp2_ = file_check_analyzer_get_files (self, dir2);
	files2 = _tmp2_;
	{
		GeeArrayList* _file1_list = NULL;
		GeeArrayList* _tmp3_;
		gint _file1_size = 0;
		GeeArrayList* _tmp4_;
		gint _tmp5_;
		gint _tmp6_;
		gint _file1_index = 0;
		_tmp3_ = files1;
		_file1_list = _tmp3_;
		_tmp4_ = _file1_list;
		_tmp5_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp4_);
		_tmp6_ = _tmp5_;
		_file1_size = _tmp6_;
		_file1_index = -1;
		while (TRUE) {
			gint _tmp7_;
			gint _tmp8_;
			gchar* file1 = NULL;
			GeeArrayList* _tmp9_;
			gpointer _tmp10_;
			gchar* file2 = NULL;
			const gchar* _tmp28_;
			_file1_index = _file1_index + 1;
			_tmp7_ = _file1_index;
			_tmp8_ = _file1_size;
			if (!(_tmp7_ < _tmp8_)) {
				break;
			}
			_tmp9_ = _file1_list;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp9_, _file1_index);
			file1 = (gchar*) _tmp10_;
			file2 = NULL;
			{
				GeeArrayList* _f_list = NULL;
				GeeArrayList* _tmp11_;
				gint _f_size = 0;
				GeeArrayList* _tmp12_;
				gint _tmp13_;
				gint _tmp14_;
				gint _f_index = 0;
				_tmp11_ = files2;
				_f_list = _tmp11_;
				_tmp12_ = _f_list;
				_tmp13_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp12_);
				_tmp14_ = _tmp13_;
				_f_size = _tmp14_;
				_f_index = -1;
				while (TRUE) {
					gint _tmp15_;
					gint _tmp16_;
					gchar* f = NULL;
					GeeArrayList* _tmp17_;
					gpointer _tmp18_;
					const gchar* _tmp19_;
					gchar* _tmp20_;
					gchar* _tmp21_;
					const gchar* _tmp22_;
					gchar* _tmp23_;
					gchar* _tmp24_;
					gboolean _tmp25_;
					_f_index = _f_index + 1;
					_tmp15_ = _f_index;
					_tmp16_ = _f_size;
					if (!(_tmp15_ < _tmp16_)) {
						break;
					}
					_tmp17_ = _f_list;
					_tmp18_ = gee_abstract_list_get ((GeeAbstractList*) _tmp17_, _f_index);
					f = (gchar*) _tmp18_;
					_tmp19_ = f;
					_tmp20_ = g_path_get_basename (_tmp19_);
					_tmp21_ = _tmp20_;
					_tmp22_ = file1;
					_tmp23_ = g_path_get_basename (_tmp22_);
					_tmp24_ = _tmp23_;
					_tmp25_ = g_strcmp0 (_tmp21_, _tmp24_) == 0;
					_g_free0 (_tmp24_);
					_g_free0 (_tmp21_);
					if (_tmp25_) {
						const gchar* _tmp26_;
						gchar* _tmp27_;
						_tmp26_ = f;
						_tmp27_ = g_strdup (_tmp26_);
						_g_free0 (file2);
						file2 = _tmp27_;
						_g_free0 (f);
						break;
					}
					_g_free0 (f);
				}
			}
			_tmp28_ = file2;
			if (_tmp28_ != NULL) {
				gchar* corruption = NULL;
				const gchar* _tmp29_;
				const gchar* _tmp30_;
				gchar* _tmp31_;
				const gchar* _tmp32_;
				_tmp29_ = file1;
				_tmp30_ = file2;
				_tmp31_ = file_check_analyzer_find_corruption (self, _tmp29_, _tmp30_, context_size);
				corruption = _tmp31_;
				_tmp32_ = corruption;
				if (g_strcmp0 (_tmp32_, "No corruption found") != 0) {
					GeeArrayList* _tmp33_;
					const gchar* _tmp34_;
					gchar* _tmp35_;
					gchar* _tmp36_;
					gchar* _tmp37_;
					gchar* _tmp38_;
					gchar* _tmp39_;
					gchar* _tmp40_;
					const gchar* _tmp41_;
					gchar* _tmp42_;
					gchar* _tmp43_;
					_tmp33_ = results;
					_tmp34_ = file1;
					_tmp35_ = g_path_get_basename (_tmp34_);
					_tmp36_ = _tmp35_;
					_tmp37_ = g_strconcat ("Corruption found in ", _tmp36_, NULL);
					_tmp38_ = _tmp37_;
					_tmp39_ = g_strconcat (_tmp38_, ": ", NULL);
					_tmp40_ = _tmp39_;
					_tmp41_ = corruption;
					_tmp42_ = g_strconcat (_tmp40_, _tmp41_, NULL);
					_tmp43_ = _tmp42_;
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp33_, _tmp43_);
					_g_free0 (_tmp43_);
					_g_free0 (_tmp40_);
					_g_free0 (_tmp38_);
					_g_free0 (_tmp36_);
				}
				_g_free0 (corruption);
			} else {
				GeeArrayList* _tmp44_;
				const gchar* _tmp45_;
				gchar* _tmp46_;
				gchar* _tmp47_;
				_tmp44_ = results;
				_tmp45_ = file1;
				_tmp46_ = g_strconcat ("File missing in dir2: ", _tmp45_, NULL);
				_tmp47_ = _tmp46_;
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp44_, _tmp47_);
				_g_free0 (_tmp47_);
			}
			_g_free0 (file2);
			_g_free0 (file1);
		}
	}
	result = results;
	_g_object_unref0 (files2);
	_g_object_unref0 (files1);
	return result;
}

GeeArrayList*
file_check_analyzer_get_files (FileCheckAnalyzer* self,
                               const gchar* directory)
{
	GeeArrayList* file_list = NULL;
	GeeArrayList* _tmp0_;
	GError* _inner_error0_ = NULL;
	GeeArrayList* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (directory != NULL, NULL);
	_tmp0_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, NULL, NULL, NULL);
	file_list = _tmp0_;
	{
		GFile* dir = NULL;
		GFile* _tmp1_;
		GFileEnumerator* enumerator = NULL;
		GFile* _tmp2_;
		GFileEnumerator* _tmp3_;
		GFileInfo* info = NULL;
		_tmp1_ = g_file_new_for_path (directory);
		dir = _tmp1_;
		_tmp2_ = dir;
		_tmp3_ = g_file_enumerate_children (_tmp2_, G_FILE_ATTRIBUTE_STANDARD_NAME, G_FILE_QUERY_INFO_NONE, NULL, &_inner_error0_);
		enumerator = _tmp3_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (dir);
			goto __catch0_g_error;
		}
		while (TRUE) {
			GFileInfo* _tmp4_ = NULL;
			GFileEnumerator* _tmp5_;
			GFileInfo* _tmp6_;
			GFileInfo* _tmp7_;
			GFileInfo* _tmp8_;
			GFile* child = NULL;
			GFile* _tmp9_;
			GFileInfo* _tmp10_;
			const gchar* _tmp11_;
			GFile* _tmp12_;
			GFile* _tmp13_;
			_tmp5_ = enumerator;
			_tmp6_ = g_file_enumerator_next_file (_tmp5_, NULL, &_inner_error0_);
			_tmp4_ = _tmp6_;
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				_g_object_unref0 (info);
				_g_object_unref0 (enumerator);
				_g_object_unref0 (dir);
				goto __catch0_g_error;
			}
			_tmp7_ = _tmp4_;
			_tmp4_ = NULL;
			_g_object_unref0 (info);
			info = _tmp7_;
			_tmp8_ = info;
			if (!(_tmp8_ != NULL)) {
				_g_object_unref0 (_tmp4_);
				break;
			}
			_tmp9_ = dir;
			_tmp10_ = info;
			_tmp11_ = g_file_info_get_name (_tmp10_);
			_tmp12_ = g_file_resolve_relative_path (_tmp9_, _tmp11_);
			child = _tmp12_;
			_tmp13_ = child;
			if (g_file_query_file_type (_tmp13_, G_FILE_QUERY_INFO_NONE, NULL) == G_FILE_TYPE_REGULAR) {
				GeeArrayList* _tmp14_;
				GFile* _tmp15_;
				gchar* _tmp16_;
				gchar* _tmp17_;
				_tmp14_ = file_list;
				_tmp15_ = child;
				_tmp16_ = g_file_get_path (_tmp15_);
				_tmp17_ = _tmp16_;
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp14_, _tmp17_);
				_g_free0 (_tmp17_);
			}
			_g_object_unref0 (child);
			_g_object_unref0 (_tmp4_);
		}
		_g_object_unref0 (info);
		_g_object_unref0 (enumerator);
		_g_object_unref0 (dir);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp18_;
		GError* _tmp19_;
		const gchar* _tmp20_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp18_ = stderr;
		_tmp19_ = e;
		_tmp20_ = _tmp19_->message;
		fprintf (_tmp18_, "Error reading directory: %s\n", _tmp20_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (file_list);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
	result = file_list;
	return result;
}

static gchar
string_get (const gchar* self,
            glong index)
{
	gchar _tmp0_;
	gchar result;
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = ((gchar*) self)[index];
	result = _tmp0_;
	return result;
}

gchar*
file_check_analyzer_find_corruption (FileCheckAnalyzer* self,
                                     const gchar* file1,
                                     const gchar* file2,
                                     gint context_size)
{
	gchar* content1 = NULL;
	gchar* content2 = NULL;
	gint _tmp5_ = 0;
	const gchar* _tmp6_;
	gint _tmp7_;
	gint _tmp8_;
	const gchar* _tmp9_;
	gint _tmp10_;
	gint _tmp11_;
	gint len = 0;
	gchar* _tmp36_;
	GError* _inner_error0_ = NULL;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (file1 != NULL, NULL);
	g_return_val_if_fail (file2 != NULL, NULL);
	{
		gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		g_file_get_contents (file1, &_tmp0_, NULL, &_inner_error0_);
		_g_free0 (content1);
		content1 = _tmp0_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		g_file_get_contents (file2, &_tmp1_, NULL, &_inner_error0_);
		_g_free0 (content2);
		content2 = _tmp1_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp2_;
		const gchar* _tmp3_;
		gchar* _tmp4_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp2_ = e;
		_tmp3_ = _tmp2_->message;
		_tmp4_ = g_strconcat ("Error reading files: ", _tmp3_, NULL);
		result = _tmp4_;
		_g_error_free0 (e);
		_g_free0 (content2);
		_g_free0 (content1);
		return result;
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_free0 (content2);
		_g_free0 (content1);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
	_tmp6_ = content1;
	_tmp7_ = strlen (_tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = content2;
	_tmp10_ = strlen (_tmp9_);
	_tmp11_ = _tmp10_;
	if (_tmp8_ < _tmp11_) {
		const gchar* _tmp12_;
		gint _tmp13_;
		gint _tmp14_;
		_tmp12_ = content1;
		_tmp13_ = strlen (_tmp12_);
		_tmp14_ = _tmp13_;
		_tmp5_ = _tmp14_;
	} else {
		const gchar* _tmp15_;
		gint _tmp16_;
		gint _tmp17_;
		_tmp15_ = content2;
		_tmp16_ = strlen (_tmp15_);
		_tmp17_ = _tmp16_;
		_tmp5_ = _tmp17_;
	}
	len = _tmp5_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp18_ = FALSE;
			_tmp18_ = TRUE;
			while (TRUE) {
				const gchar* _tmp20_;
				const gchar* _tmp21_;
				if (!_tmp18_) {
					gint _tmp19_;
					_tmp19_ = i;
					i = _tmp19_ + 1;
				}
				_tmp18_ = FALSE;
				if (!(i < len)) {
					break;
				}
				_tmp20_ = content1;
				_tmp21_ = content2;
				if (string_get (_tmp20_, (glong) i) != string_get (_tmp21_, (glong) i)) {
					gint start = 0;
					gint end = 0;
					const gchar* _tmp22_;
					gint _tmp23_;
					gint _tmp24_;
					const gchar* _tmp28_;
					gint _tmp29_;
					gint _tmp30_;
					start = i - context_size;
					end = i + context_size;
					if (start < 0) {
						start = 0;
					}
					_tmp22_ = content1;
					_tmp23_ = strlen (_tmp22_);
					_tmp24_ = _tmp23_;
					if (end > _tmp24_) {
						const gchar* _tmp25_;
						gint _tmp26_;
						gint _tmp27_;
						_tmp25_ = content1;
						_tmp26_ = strlen (_tmp25_);
						_tmp27_ = _tmp26_;
						end = _tmp27_;
					}
					_tmp28_ = content2;
					_tmp29_ = strlen (_tmp28_);
					_tmp30_ = _tmp29_;
					if (end > _tmp30_) {
						const gchar* _tmp31_;
						gint _tmp32_;
						gint _tmp33_;
						_tmp31_ = content2;
						_tmp32_ = strlen (_tmp31_);
						_tmp33_ = _tmp32_;
						end = _tmp33_;
					}
					if (start < end) {
						gchar* _tmp34_;
						_tmp34_ = g_strdup_printf ("Difference at position %d", i);
						result = _tmp34_;
						_g_free0 (content2);
						_g_free0 (content1);
						return result;
					} else {
						gchar* _tmp35_;
						_tmp35_ = g_strdup_printf ("Difference at position %d: context not available", i);
						result = _tmp35_;
						_g_free0 (content2);
						_g_free0 (content1);
						return result;
					}
				}
			}
		}
	}
	_tmp36_ = g_strdup ("No corruption found");
	result = _tmp36_;
	_g_free0 (content2);
	_g_free0 (content1);
	return result;
}

static void
file_check_value_analyzer_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
file_check_value_analyzer_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		file_check_analyzer_unref (value->data[0].v_pointer);
	}
}

static void
file_check_value_analyzer_copy_value (const GValue* src_value,
                                      GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = file_check_analyzer_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
file_check_value_analyzer_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
file_check_value_analyzer_collect_value (GValue* value,
                                         guint n_collect_values,
                                         GTypeCValue* collect_values,
                                         guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		FileCheckAnalyzer * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = file_check_analyzer_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
file_check_value_analyzer_lcopy_value (const GValue* value,
                                       guint n_collect_values,
                                       GTypeCValue* collect_values,
                                       guint collect_flags)
{
	FileCheckAnalyzer ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = file_check_analyzer_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
file_check_param_spec_analyzer (const gchar* name,
                                const gchar* nick,
                                const gchar* blurb,
                                GType object_type,
                                GParamFlags flags)
{
	FileCheckParamSpecAnalyzer* spec;
	g_return_val_if_fail (g_type_is_a (object_type, FILE_CHECK_TYPE_ANALYZER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
file_check_value_get_analyzer (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, FILE_CHECK_TYPE_ANALYZER), NULL);
	return value->data[0].v_pointer;
}

void
file_check_value_set_analyzer (GValue* value,
                               gpointer v_object)
{
	FileCheckAnalyzer * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, FILE_CHECK_TYPE_ANALYZER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, FILE_CHECK_TYPE_ANALYZER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		file_check_analyzer_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		file_check_analyzer_unref (old);
	}
}

void
file_check_value_take_analyzer (GValue* value,
                                gpointer v_object)
{
	FileCheckAnalyzer * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, FILE_CHECK_TYPE_ANALYZER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, FILE_CHECK_TYPE_ANALYZER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		file_check_analyzer_unref (old);
	}
}

static void
file_check_analyzer_class_init (FileCheckAnalyzerClass * klass,
                                gpointer klass_data)
{
	file_check_analyzer_parent_class = g_type_class_peek_parent (klass);
	((FileCheckAnalyzerClass *) klass)->finalize = file_check_analyzer_finalize;
}

static void
file_check_analyzer_instance_init (FileCheckAnalyzer * self,
                                   gpointer klass)
{
	self->ref_count = 1;
}

static void
file_check_analyzer_finalize (FileCheckAnalyzer * obj)
{
	FileCheckAnalyzer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, FILE_CHECK_TYPE_ANALYZER, FileCheckAnalyzer);
	g_signal_handlers_destroy (self);
}

static GType
file_check_analyzer_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { file_check_value_analyzer_init, file_check_value_analyzer_free_value, file_check_value_analyzer_copy_value, file_check_value_analyzer_peek_pointer, "p", file_check_value_analyzer_collect_value, "p", file_check_value_analyzer_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (FileCheckAnalyzerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) file_check_analyzer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FileCheckAnalyzer), 0, (GInstanceInitFunc) file_check_analyzer_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType file_check_analyzer_type_id;
	file_check_analyzer_type_id = g_type_register_fundamental (g_type_fundamental_next (), "FileCheckAnalyzer", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return file_check_analyzer_type_id;
}

GType
file_check_analyzer_get_type (void)
{
	static volatile gsize file_check_analyzer_type_id__once = 0;
	if (g_once_init_enter (&file_check_analyzer_type_id__once)) {
		GType file_check_analyzer_type_id;
		file_check_analyzer_type_id = file_check_analyzer_get_type_once ();
		g_once_init_leave (&file_check_analyzer_type_id__once, file_check_analyzer_type_id);
	}
	return file_check_analyzer_type_id__once;
}

gpointer
file_check_analyzer_ref (gpointer instance)
{
	FileCheckAnalyzer * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
file_check_analyzer_unref (gpointer instance)
{
	FileCheckAnalyzer * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		FILE_CHECK_ANALYZER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

