/* filecheck.vapi generated by valac 0.56.17, do not modify. */

namespace FileCheck {
	[CCode (cheader_filename = "filecheck.h")]
	public class Analyzer {
		public Analyzer ();
		public Gee.ArrayList<string> analyze_directories (string dir1, string dir2, int context_size);
		public string find_corruption (string file1, string file2, int context_size);
		public Gee.ArrayList<string> get_files (string directory);
	}
}
