/* filecheck.vapi generated by valac 0.56.17, do not modify. */

namespace FileCheck {
	[CCode (cheader_filename = "filecheck.h")]
	public class Analyzer {
		public int CONTEXT_SIZE;
		public Analyzer ();
		public void compare_directory (GLib.File original_dir, GLib.File corrupted_dir, Gee.ArrayList<string> results);
	}
}
